// src/saas/features/listing-editor/components/paving-canvas.component.ts
import { Component, OnInit, AfterViewInit, OnDestroy, effect, signal, computed, inject, viewChild, ElementRef, ChangeDetectionStrategy } from '@angular/core';
import { CommonModule } from '@angular/common';
import { PavingStoreService } from '../services/paving-store.service';
import { SECTION_TYPES, SECTION_LIBRARY, generateBlockId } from '../constants/paving.constants';
import { PavingBlockComponent, type PavingBlock, type AdjacentEdges } from './paving-block.component';
import type { Section, SectionType, GridBlock } from '../models/paving.types';

const TARGET_VIEW_HEIGHT = 600;
const DELETE_THRESHOLD = 15;
const SNAP_THRESHOLD = 10;
const BORDER_HIT_AREA = 8;
const EPSILON = 1;

interface ActiveEdge {
  orientation: 'V' | 'H';
  coordinate: number;
  affectedA: string[];
  affectedB: string[];
}

interface History {
  past: PavingBlock[][];
  future: PavingBlock[][];
}

function refreshLayoutPositions(currentBlocks: PavingBlock[]): PavingBlock[] {
  if (currentBlocks.length === 0) return [];
  const sorted = [...currentBlocks].sort((a, b) => a.y - b.y || a.x - b.x);
  const segments: { y: number; h: number; blockIds: string[] }[] = [];
  sorted.forEach(block => {
    const segment = segments.find(s => Math.abs(s.y - block.y) < EPSILON);
    if (segment) {
      segment.blockIds.push(block.id);
      segment.h = Math.max(segment.h, block.h);
    } else {
      segments.push({ y: block.y, h: block.h, blockIds: [block.id] });
    }
  });
  let currentY = 0;
  const updated = [...currentBlocks];
  segments.forEach(seg => {
    seg.blockIds.forEach(id => {
      const bIdx = updated.findIndex(b => b.id === id);
      updated[bIdx] = { ...updated[bIdx], y: currentY, h: seg.h };
    });
    currentY += seg.h;
  });
  return updated;
}

@Component({
  selector: 'app-paving-canvas',
  standalone: true,
  imports: [CommonModule, PavingBlockComponent],
  templateUrl: './paving-canvas.component.html',
  styleUrls: ['../styles/paving-editor.css'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class PavingCanvasComponent implements OnInit, AfterViewInit, OnDestroy {
  store = inject(PavingStoreService);

  _blocks = signal<PavingBlock[]>([]);
  _history = signal<History>({ past: [], future: [] });
  _activeEdge = signal<ActiveEdge | null>(null);
  _message = signal<string | null>(null);
  _canvasActualWidth = signal(800);
  _frameWidth = computed(() => Math.max(400, this._canvasActualWidth()));
  _canvasHeight = computed(() => {
    const b = this._blocks();
    return Math.max(TARGET_VIEW_HEIGHT, 0, ...b.map(bl => bl.y + bl.h)) + 100;
  });
  _minSize = computed(() => Math.max(50, this._frameWidth() / 16));

  private _canvasRef = viewChild<ElementRef<HTMLElement>>('canvasRef');
  private _wrapperRef = viewChild<ElementRef<HTMLElement>>('wrapperRef');
  private _clickTimeout: ReturnType<typeof setTimeout> | null = null;
  private _initialized = false;
  private _resizeObserver: ResizeObserver | null = null;
  private _prevFrameWidth = signal(0);
  private _resizeBlockTimer: ReturnType<typeof setTimeout> | null = null;

  adjacentEdgesMap = computed(() => {
    const blockList = this._blocks();
    const selected = this.store.selectedBlockIds();
    const map = new Map<string, AdjacentEdges>();
    for (const block of blockList) {
      if (selected.includes(block.id)) {
        map.set(block.id, getAdjacentEdges(block.id, blockList));
      }
    }
    return map;
  });

  sectionNameMap = computed(() => {
    const blockList = this._blocks();
    const storeBlocks = this.store.gridBlocks();
    const storeSections = this.store.pageConfig().sections;
    const map = new Map<string, string | null>();
    for (const block of blockList) {
      const gb = storeBlocks.find(g => g.id === block.id);
      if (gb?.sectionId) {
        const section = storeSections.find(s => s.id === gb.sectionId);
        if (section) {
          const info = SECTION_TYPES.find(st => st.type === section.type);
          map.set(block.id, info ? `${info.icon} ${info.label}` : section.type);
        } else {
          map.set(block.id, null);
        }
      } else {
        map.set(block.id, null);
      }
    }
    return map;
  });

  sectionMap = computed(() => {
    const blockList = this._blocks();
    const storeBlocks = this.store.gridBlocks();
    const storeSections = this.store.pageConfig().sections;
    const map = new Map<string, Section | null>();
    for (const block of blockList) {
      const gb = storeBlocks.find(g => g.id === block.id);
      if (gb?.sectionId) {
        const section = storeSections.find(s => s.id === gb.sectionId) || null;
        map.set(block.id, section);
      } else {
        map.set(block.id, null);
      }
    }
    return map;
  });

  isLayoutEditing = computed(() => this.store.editorMode() === 'layout');

  constructor() {
    effect(() => {
      const currentBlocks = this._blocks();
      if (!this._initialized || currentBlocks.length === 0) return;

      const currentGridBlocks = this.store.gridBlocks();
      const next: GridBlock[] = currentBlocks.map(b => {
        const existing = currentGridBlocks.find(g => g.id === b.id);
        return {
          id: b.id,
          sectionId: b.section.id !== 'S0' ? b.section.id : undefined,
          row: 0,
          col: 0,
          bounds: { top: b.y, left: b.x, right: b.x + b.w, bottom: b.y + b.h },
          displayMode: b.section.displayMode,
          blockStyle: existing?.blockStyle,
        };
      });

      const prev = currentGridBlocks;
      const changed = prev.length !== next.length || prev.some((g, i) =>
        g.id !== next[i]?.id ||
        g.bounds.top !== next[i].bounds.top ||
        g.bounds.left !== next[i].bounds.left ||
        g.bounds.right !== next[i].bounds.right ||
        g.bounds.bottom !== next[i].bounds.bottom ||
        g.sectionId !== next[i].sectionId
      );

      if (changed) {
        this.store.setGridBlocks(next);
      }
    });

    effect(() => {
      const storeBlocks = this.store.gridBlocks();
      const sections = this.store.pageConfig().sections;
      if (!this._initialized) return;

      const localBlocks = this._blocks();
      let changed = false;
      const next: PavingBlock[] = localBlocks.map(b => {
        const gb = storeBlocks.find(g => g.id === b.id);
        if (gb?.sectionId && gb.sectionId !== b.section.id) {
          changed = true;
          const section = sections.find(s => s.id === gb.sectionId);
          const libItem = section ? SECTION_LIBRARY.find(item => item.type === section?.type) : null;
          return {
            ...b,
            section: {
              ...b.section,
              id: gb.sectionId,
              color: libItem?.color || '#3b82f6',
              type: section?.type || 'ADAPTIVE',
              displayMode: 'LOCKED',
              requestedWidth: (section?.content as any)?.requestedWidth || 0,
              requestedHeight: (section?.content as any)?.requestedHeight || 0,
              style: { ...(section?.style || {}), ...(gb.blockStyle || {}) },
            },
          };
        }
        if (gb && !gb.sectionId && b.section.id !== 'S0') {
          changed = true;
          return {
            ...b,
            section: { ...b.section, id: 'S0', color: '#1e293b', type: 'ADAPTIVE', displayMode: 'UNLOCKED', style: {} },
          };
        }
        return b;
      });

      if (changed) {
        this._blocks.set(next);
      }
    });

    effect(() => {
      const fw = this._frameWidth();
      const prev = this._prevFrameWidth();
      if (!this._initialized || prev === 0 || fw === prev) {
        this._prevFrameWidth.set(fw);
        return;
      }
      const scale = fw / prev;
      if (Math.abs(scale - 1) < 0.01) {
        this._prevFrameWidth.set(fw);
        return;
      }
      const blocks = this._blocks();
      if (blocks.length === 0) {
        this._prevFrameWidth.set(fw);
        return;
      }
      const allFullWidth = blocks.every(b => b.x === 0 && Math.abs(b.w - prev) < 2);
      if (allFullWidth) {
        this._blocks.update(prevBlocks =>
          prevBlocks.map(b => ({ ...b, w: fw }))
        );
      } else {
        this._blocks.update(prevBlocks =>
          prevBlocks.map(b => ({
            ...b,
            x: Math.round(b.x * scale),
            w: Math.max(50, Math.round(b.w * scale)),
          }))
        );
      }
      this._prevFrameWidth.set(fw);
    });
  }

  ngOnInit(): void {
    const storeGridBlocks = this.store.gridBlocks();
    const storeSections = this.store.pageConfig().sections;

    if (storeGridBlocks.length > 0) {
      this._blocks.set(storeGridBlocks.map(gb => {
        const section = gb.sectionId ? storeSections.find(s => s.id === gb.sectionId) : null;
        const sectionType: SectionType = section ? section.type : 'ADAPTIVE';
        const libItem = section ? SECTION_LIBRARY.find(item => item.type === sectionType) : null;
        return {
          id: gb.id,
          x: gb.bounds.left,
          y: gb.bounds.top,
          w: gb.bounds.right - gb.bounds.left,
          h: gb.bounds.bottom - gb.bounds.top,
          section: {
            id: gb.sectionId || 'S0',
            color: section ? libItem?.color || '#3b82f6' : '#1e293b',
            type: sectionType,
            requestedWidth: section ? (section.content as any)?.requestedWidth || 0 : 0,
            requestedHeight: section ? (section.content as any)?.requestedHeight || 0 : 0,
            displayMode: (gb.sectionId ? 'LOCKED' : 'UNLOCKED') as 'LOCKED' | 'UNLOCKED',
            style: { ...(section?.style || {}), ...(gb.blockStyle || {}) },
          },
        };
      }));
    } else {
      const initialH = TARGET_VIEW_HEIGHT / 4;
      const initBlocks = Array.from({ length: 4 }).map((_, i) => ({
        id: generateBlockId(),
        x: 0,
        y: i * initialH,
        w: this._frameWidth(),
        h: initialH,
        section: {
          id: 'S0' as const,
          color: '#1e293b',
          type: 'ADAPTIVE' as SectionType,
          requestedWidth: 200,
          requestedHeight: 150,
          displayMode: 'UNLOCKED' as 'LOCKED' | 'UNLOCKED',
        },
      }));
      this._blocks.set(initBlocks);
    }

    this._initialized = true;
    this._prevFrameWidth.set(this._frameWidth());
  }

  ngAfterViewInit(): void {
    const el = this._canvasRef()?.nativeElement;
    if (el) {
      this._canvasActualWidth.set(el.clientWidth);
      this._resizeObserver = new ResizeObserver(entries => {
        for (const entry of entries) {
          const w = entry.contentRect.width;
          if (w > 0) this._canvasActualWidth.set(Math.round(w));
        }
      });
      this._resizeObserver.observe(el);
    }
  }

  ngOnDestroy(): void {
    this._resizeObserver?.disconnect();
    this._resizeObserver = null;
  }

  saveHistory(): void {
    this._history.update(prev => ({
      past: [...prev.past.slice(-29), this._blocks()],
      future: [],
    }));
  }

  undo(): void {
    const h = this._history();
    if (h.past.length === 0) return;
    const previous = h.past[h.past.length - 1];
    this._history.set({ past: h.past.slice(0, -1), future: [this._blocks(), ...h.future] });
    this._blocks.set(previous);
    this.store.clearBlockSelection();
  }

  redo(): void {
    const h = this._history();
    if (h.future.length === 0) return;
    const next = h.future[0];
    this._history.set({ past: [...h.past, this._blocks()], future: h.future.slice(1) });
    this._blocks.set(next);
    this.store.clearBlockSelection();
  }

  handleSplitV(id: string): void {
    const blocks = this._blocks();
    const idx = blocks.findIndex(b => b.id === id);
    const target = blocks[idx];
    if (!target || target.w < this._minSize() * 2) {
      this._message.set(`Block too narrow to split (min ${this._minSize()}px)`);
      setTimeout(() => this._message.set(null), 2000);
      return;
    }
    this.saveHistory();
    const halfW = Math.round(target.w / 2);
    const newBlock: PavingBlock = {
      ...target,
      id: generateBlockId(),
      x: target.x + halfW,
      w: target.w - halfW,
      section: { ...target.section, id: 'S0', color: '#1e293b', type: 'ADAPTIVE', displayMode: 'UNLOCKED' },
    };
    const updated = [...blocks];
    updated[idx] = { ...target, w: halfW };
    updated.splice(idx + 1, 0, newBlock);
    this._blocks.set(updated);
  }

  handleSplitH(id: string): void {
    const blocks = this._blocks();
    const idx = blocks.findIndex(b => b.id === id);
    const target = blocks[idx];
    if (!target || target.h < this._minSize() * 2) {
      this._message.set(`Block too short to split (min ${this._minSize()}px)`);
      setTimeout(() => this._message.set(null), 2000);
      return;
    }
    this.saveHistory();
    const halfH = Math.round(target.h / 2);
    const newBlock: PavingBlock = {
      ...target,
      id: generateBlockId(),
      y: target.y + halfH,
      h: target.h - halfH,
      section: { ...target.section, id: 'S0', color: '#1e293b', type: 'ADAPTIVE', displayMode: 'UNLOCKED' },
    };
    const updated = [...blocks];
    updated[idx] = { ...target, h: halfH };
    updated.splice(idx + 1, 0, newBlock);
    this._blocks.set(updated);
  }

  handleMerge(): void {
    const selected = this.store.selectedBlockIds();
    if (selected.length !== 2) return;

    const blocks = this._blocks();
    const b1 = blocks.find(b => b.id === selected[0]);
    const b2 = blocks.find(b => b.id === selected[1]);
    if (!b1 || !b2) return;

    const touchX = Math.abs(b1.x + b1.w - b2.x) < EPSILON || Math.abs(b2.x + b2.w - b1.x) < EPSILON;
    const touchY = Math.abs(b1.y + b1.h - b2.y) < EPSILON || Math.abs(b2.y + b2.h - b1.y) < EPSILON;
    const overlapY = Math.max(b1.y, b2.y) < Math.min(b1.y + b1.h, b2.y + b2.h);
    const overlapX = Math.max(b1.x, b2.x) < Math.min(b1.x + b1.w, b2.x + b2.w);
    const adjacent = (touchX && overlapY) || (touchY && overlapX);
    const newX = Math.min(b1.x, b2.x);
    const newY = Math.min(b1.y, b2.y);
    const newW = Math.max(b1.x + b1.w, b2.x + b2.w) - newX;
    const newH = Math.max(b1.y + b1.h, b2.y + b2.h) - newY;
    const areaSum = (b1.w * b1.h) + (b2.w * b2.h);

    if (!adjacent || Math.abs(areaSum - (newW * newH)) > 10) {
      this._message.set('Merge failed: Blocks must form a perfect rectangle.');
      setTimeout(() => this._message.set(null), 2000);
      return;
    }

    this.saveHistory();
    const merged: PavingBlock = {
      id: generateBlockId(),
      x: newX,
      y: newY,
      w: newW,
      h: newH,
      section: { ...b1.section },
    };
    this._blocks.set(refreshLayoutPositions([...blocks.filter(b => !selected.includes(b.id)), merged]));
    this.store.clearBlockSelection();
  }

  handleAddBlock(): void {
    this.saveHistory();
    const maxBottom = this._blocks().length > 0 ? Math.max(...this._blocks().map(b => b.y + b.h)) : 0;
    const newBlock: PavingBlock = {
      id: generateBlockId(),
      x: 0,
      y: maxBottom,
      w: this._frameWidth(),
      h: Math.max(100, TARGET_VIEW_HEIGHT / 6),
      section: { id: 'S0', color: '#1e293b', type: 'ADAPTIVE', requestedWidth: 200, requestedHeight: 150, displayMode: 'UNLOCKED' },
    };
    this._blocks.update(prev => [...prev, newBlock]);
    this.store.setSelectedBlock(newBlock.id);
  }

  handleToggleLock(id: string): void {
    this.saveHistory();
    this._blocks.update(prev => prev.map(b =>
      b.id === id
        ? { ...b, section: { ...b.section, displayMode: b.section.displayMode === 'LOCKED' ? 'UNLOCKED' : 'LOCKED' } }
        : b
    ));
  }

  handleBlockDrop(evt: { blockId: string; data: string }): void {
    const libSection = JSON.parse(evt.data);
    this.saveHistory();
    this._blocks.update(prev => prev.map(b =>
      b.id === evt.blockId
        ? {
            ...b,
            section: {
              id: libSection.id,
              color: libSection.color,
              type: libSection.type,
              requestedWidth: libSection.rW || 0,
              requestedHeight: libSection.rH || 0,
              displayMode: libSection.id === 'S0' ? 'UNLOCKED' : 'LOCKED',
            },
          }
        : b
    ));
  }

  onBlockClick(evt: { event: MouseEvent; block: PavingBlock }): void {
    const { event: e, block } = evt;
    const editorMode = this.store.editorMode();

    if (editorMode === 'layout') {
      const isShift = e.shiftKey;
      const isSelected = this.store.selectedBlockIds().includes(block.id);
      let next: string[];
      if (isShift) {
        if (isSelected) {
          next = this.store.selectedBlockIds().filter(id => id !== block.id);
        } else {
          next = [...this.store.selectedBlockIds(), block.id].slice(0, 2);
        }
      } else {
        next = [block.id];
      }
      this.store.clearBlockSelection();
      if (next.length === 1) {
        this.store.setSelectedBlock(next[0]);
      } else {
        this.store.selectedBlockIds.set(next);
        this.store.selectedBlockId.set(null);
      }
      return;
    }

    if (editorMode === 'display') {
      if (this._clickTimeout) {
        clearTimeout(this._clickTimeout);
        this._clickTimeout = null;
      }
      this._clickTimeout = setTimeout(() => {
        this.store.setEditorMode('layout');
        this.store.setSelectedBlock(block.id);
        this.store.sidebarOpen.set(false);
        this._clickTimeout = null;
      }, 250);
    }
  }

  onBlockDoubleClick(evt: { event: MouseEvent; block: PavingBlock }): void {
    const block = evt.block;
    if (this._clickTimeout) {
      clearTimeout(this._clickTimeout);
      this._clickTimeout = null;
    }

    const editorMode = this.store.editorMode();
    if (editorMode === 'display' || editorMode === 'config') {
      this.store.setEditorMode('config');
      this.store.setSelectedBlock(block.id);
      const isS0 = block.section.id === 'S0';
      this.store.sidebarOpen.set(true);
      this.store.setSelectedSection(isS0 ? null : block.section.id);
    }
  }

  onMouseDown(event: MouseEvent): void {
    if (this.store.editorMode() !== 'layout') return;
    const canvasEl = this._canvasRef()?.nativeElement;
    if (!canvasEl) return;
    const rect = canvasEl.getBoundingClientRect();
    const mx = event.clientX - rect.left;
    const my = event.clientY - rect.top;

    const blocks = this._blocks();
    for (const b of blocks) {
      if (Math.abs(mx - (b.x + b.w)) < BORDER_HIT_AREA && my >= b.y && my <= b.y + b.h && b.x + b.w < this._frameWidth()) {
        this.saveHistory();
        this._activeEdge.set({
          orientation: 'V',
          coordinate: b.x + b.w,
          affectedA: blocks.filter(bl => Math.abs(bl.x + bl.w - (b.x + b.w)) < EPSILON).map(bl => bl.id),
          affectedB: blocks.filter(bl => Math.abs(bl.x - (b.x + b.w)) < EPSILON).map(bl => bl.id),
        });
        return;
      }
      if (Math.abs(my - (b.y + b.h)) < BORDER_HIT_AREA && mx >= b.x && mx <= b.x + b.w) {
        this.saveHistory();
        this._activeEdge.set({
          orientation: 'H',
          coordinate: b.y + b.h,
          affectedA: blocks.filter(bl => Math.abs(bl.y + bl.h - (b.y + b.h)) < EPSILON).map(bl => bl.id),
          affectedB: blocks.filter(bl => Math.abs(bl.y - (b.y + b.h)) < EPSILON).map(bl => bl.id),
        });
        return;
      }
      if (Math.abs(mx - b.x) < BORDER_HIT_AREA && my >= b.y && my <= b.y + b.h) {
        this.saveHistory();
        this._activeEdge.set({
          orientation: 'V',
          coordinate: b.x,
          affectedA: blocks.filter(bl => Math.abs(bl.x - b.x) < EPSILON).map(bl => bl.id),
          affectedB: blocks.filter(bl => Math.abs(bl.x + bl.w - b.x) < EPSILON).map(bl => bl.id),
        });
        return;
      }
      if (Math.abs(my - b.y) < BORDER_HIT_AREA && mx >= b.x && mx <= b.x + b.w) {
        this.saveHistory();
        this._activeEdge.set({
          orientation: 'H',
          coordinate: b.y,
          affectedA: blocks.filter(bl => Math.abs(bl.y - b.y) < EPSILON).map(bl => bl.id),
          affectedB: blocks.filter(bl => Math.abs(bl.y + bl.h - b.y) < EPSILON).map(bl => bl.id),
        });
        return;
      }
    }
  }

  onMouseMove(event: MouseEvent): void {
    const ae = this._activeEdge();
    if (!ae) return;
    const canvasEl = this._canvasRef()?.nativeElement;
    if (!canvasEl) return;
    const rect = canvasEl.getBoundingClientRect();
    const rawPos = ae.orientation === 'V' ? event.clientX - rect.left : event.clientY - rect.top;

    let pos = rawPos;
    if (ae.orientation === 'V') {
      pos = Math.max(0, Math.min(this._frameWidth(), pos));
    } else {
      pos = Math.max(0, pos);
    }

    const snapPoints = new Set<number>();
    if (ae.orientation === 'V') {
      snapPoints.add(0);
      snapPoints.add(this._frameWidth());
      this._blocks().forEach(b => { snapPoints.add(b.x); snapPoints.add(b.x + b.w); });
    } else {
      snapPoints.add(0);
      this._blocks().forEach(b => { snapPoints.add(b.y); snapPoints.add(b.y + b.h); });
    }
    for (const point of snapPoints) {
      if (Math.abs(pos - point) < SNAP_THRESHOLD) { pos = point; break; }
    }

    const initialCoord = ae.coordinate;
    const checkClamping = (blockIds: string[], type: 'A' | 'B') => {
      for (const id of blockIds) {
        const b = this._blocks().find(x => x.id === id);
        if (!b) continue;
        let newDim: number;
        if (type === 'A') {
          newDim = (ae.orientation === 'V' ? b.w : b.h) + (pos - initialCoord);
        } else {
          newDim = (ae.orientation === 'V' ? b.w : b.h) - (pos - initialCoord);
        }
        if (newDim < this._minSize() && newDim > DELETE_THRESHOLD) {
          if (type === 'A') {
            pos = ae.orientation === 'V' ? b.x + this._minSize() : b.y + this._minSize();
          } else {
            pos = ae.orientation === 'V' ? (b.x + b.w) - this._minSize() : (b.y + b.h) - this._minSize();
          }
        } else if (newDim <= DELETE_THRESHOLD) {
          pos = type === 'A'
            ? (ae.orientation === 'V' ? b.x : b.y)
            : (ae.orientation === 'V' ? b.x + b.w : b.y + b.h);
        }
      }
    };
    checkClamping(ae.affectedA, 'A');
    checkClamping(ae.affectedB, 'B');

    const delta = pos - ae.coordinate;
    this._blocks.update(prev => {
      const next = prev.map(b => {
        if (ae.affectedA.includes(b.id)) {
          return ae.orientation === 'V' ? { ...b, w: b.w + delta } : { ...b, h: b.h + delta };
        }
        if (ae.affectedB.includes(b.id)) {
          return ae.orientation === 'V' ? { ...b, x: b.x + delta, w: b.w - delta } : { ...b, y: b.y + delta, h: b.h - delta };
        }
        return b;
      });
      const kept = next.filter(b => b.w > 2 && b.h > 2);
      return kept.length !== next.length ? refreshLayoutPositions(kept) : next;
    });
    this._activeEdge.update(prev => prev ? { ...prev, coordinate: pos } : null);

    if (ae.orientation === 'H') {
      const wrapper = this._wrapperRef()?.nativeElement;
      if (wrapper) {
        const scrollBottom = wrapper.scrollTop + wrapper.clientHeight;
        if (pos > scrollBottom - 50) {
          wrapper.scrollTop = pos - wrapper.clientHeight + 100;
        }
      }
    }
  }

  onMouseUp(): void {
    this._activeEdge.set(null);
  }

  onBottomResizeStart(event: MouseEvent): void {
    event.stopPropagation();
    this.saveHistory();
    const blocks = this._blocks();
    const maxH = Math.max(...blocks.map(b => b.y + b.h));
    const bottomBlocks = blocks.filter(b => Math.abs(b.y + b.h - maxH) < EPSILON);
    if (bottomBlocks.length === 0) return;
    this._activeEdge.set({
      orientation: 'H',
      coordinate: maxH,
      affectedA: bottomBlocks.map(b => b.id),
      affectedB: [],
    });
  }

  onCanvasClick(event: MouseEvent): void {
    const canvasEl = this._canvasRef()?.nativeElement;
    if (canvasEl && event.target === canvasEl && this.store.editorMode() !== 'layout') {
      this.store.setEditorMode('display');
      this.store.clearBlockSelection();
      this.store.sidebarOpen.set(false);
    }
  }

  onWrapperClick(event: MouseEvent): void {
    if (event.target === event.currentTarget && this.store.editorMode() !== 'layout') {
      this.store.setEditorMode('display');
      this.store.clearBlockSelection();
      this.store.sidebarOpen.set(false);
    }
  }
}

function getAdjacentEdges(blockId: string, allBlocks: PavingBlock[]): AdjacentEdges {
  const block = allBlocks.find(b => b.id === blockId);
  if (!block) return { top: false, right: false, bottom: false, left: false };

  return {
    top: allBlocks.some(b =>
      b.id !== blockId &&
      Math.abs(b.y + b.h - block.y) < 1 &&
      b.x < block.x + block.w && b.x + b.w > block.x
    ),
    right: allBlocks.some(b =>
      b.id !== blockId &&
      Math.abs(b.x - (block.x + block.w)) < 1 &&
      b.y < block.y + block.h && b.y + b.h > block.y
    ),
    bottom: allBlocks.some(b =>
      b.id !== blockId &&
      Math.abs(b.y - (block.y + block.h)) < 1 &&
      b.x < block.x + block.w && b.x + b.w > block.x
    ),
    left: allBlocks.some(b =>
      b.id !== blockId &&
      Math.abs(b.x + b.w - block.x) < 1 &&
      b.y < block.y + block.h && b.y + b.h > block.y
    ),
  };
}

<div class="paving-engine"
  [class.mode-display]="store.editorMode() === 'display'"
  [class.mode-layout]="store.editorMode() === 'layout'"
  [class.mode-config]="store.editorMode() === 'config'">

  @if (_message(); as msg) {
    <div class="paving-toast">
      <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
        <circle cx="12" cy="12" r="10"></circle>
        <line x1="12" y1="16" x2="12" y2="12"></line>
        <line x1="12" y1="8" x2="12.01" y2="8"></line>
      </svg>
      {{ msg }}
    </div>
  }

  <div class="paving-body">
    <div #wrapperRef class="paving-canvas-wrapper" style="overflow-y: auto; position: relative"
      (click)="onWrapperClick($event)">

      @if (isLayoutEditing()) {
        <div class="paving-floating-toolbar">
          <button (click)="undo()" [disabled]="_history().past.length === 0" title="Undo"
            class="paving-floating-btn">
            <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
              <polyline points="1 4 1 10 7 10"></polyline>
              <path d="M3.51 15a9 9 0 1 0 2.13-9.36L1 10"></path>
            </svg>
          </button>
          <button (click)="redo()" [disabled]="_history().future.length === 0" title="Redo"
            class="paving-floating-btn">
            <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
              <polyline points="23 4 23 10 17 10"></polyline>
              <path d="M20.49 15a9 9 0 1 1-2.12-9.36L23 10"></path>
            </svg>
          </button>
          <button (click)="handleAddBlock()" title="Add block"
            class="paving-floating-btn">
            <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
              <line x1="12" y1="5" x2="12" y2="19"></line>
              <line x1="5" y1="12" x2="19" y2="12"></line>
            </svg>
          </button>
          <button (click)="handleMerge()" [disabled]="store.selectedBlockIds().length !== 2" title="Merge selected blocks"
            class="paving-floating-btn">
            <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
              <rect x="2" y="2" width="8" height="8" rx="1"></rect>
              <rect x="14" y="2" width="8" height="8" rx="1"></rect>
              <rect x="8" y="14" width="8" height="8" rx="1"></rect>
            </svg>
          </button>
        </div>
      }

      <div #canvasRef
        class="paving-canvas"
        [style.height.px]="_canvasHeight()"
        [style.cursor]="_activeEdge() ? (_activeEdge()!.orientation === 'V' ? 'col-resize' : 'row-resize') : 'default'"
        (mousedown)="onMouseDown($event)"
        (mousemove)="onMouseMove($event)"
        (mouseup)="onMouseUp()"
        (mouseleave)="onMouseUp()"
        (click)="onCanvasClick($event)">

        @for (block of _blocks(); track block.id) {
          <app-paving-block
            [block]="block"
            [isSelected]="store.selectedBlockIds().includes(block.id)"
            [editorMode]="store.editorMode()"
            [frameWidth]="_frameWidth()"
            [adjacentEdges]="adjacentEdgesMap().get(block.id) || { top: false, right: false, bottom: false, left: false }"
            [sectionName]="sectionNameMap().get(block.id) || null"
            [sectionObj]="sectionMap().get(block.id) || null"
            (blockClick)="onBlockClick($event)"
            (blockDoubleClick)="onBlockDoubleClick($event)"
            (splitVertical)="handleSplitV($event)"
            (splitHorizontal)="handleSplitH($event)"
            (toggleLock)="handleToggleLock($event)"
            (blockDrop)="handleBlockDrop($event)" />
        }

        @if (isLayoutEditing()) {
          <div class="paving-bottom-handle"
            (mousedown)="onBottomResizeStart($event)"
            style="position: absolute; left: 0; right: 0; bottom: 0; height: 24px; cursor: row-resize; z-index: 10; display: flex; align-items: center; justify-content: center;">
            <div style="width: 60px; height: 4px; background: #cbd5e1; border-radius: 2px;"></div>
          </div>
        }
      </div>
    </div>
  </div>
</div>

// src/listing-editor/components/PavingCanvas.tsx
import React, { useState, useEffect, useRef } from 'react';
import { Lock, Unlock, Scissors, Merge, Info, Undo2, Redo2 } from 'lucide-react';
import { useEditorStore } from '../store/useEditorStore';
import { SECTION_TYPES, SECTION_LIBRARY } from '../lib/constants';
import type { SectionStyle, SectionType } from '../types/index';


// --- Constants ---
const FRAME_WIDTH = 800;
const TARGET_VIEW_HEIGHT = 600;
const MIN_SIZE = FRAME_WIDTH / 16;
const DELETE_THRESHOLD = 15;
const SNAP_THRESHOLD = 10;
const BORDER_HIT_AREA = 8;
const EPSILON = 1;

// --- Types ---
type DisplayMode = 'LOCKED' | 'UNLOCKED';

const generateBlockId = () => 'blk_' + Date.now() + '_' + Math.random().toString(36).substr(2, 9);

interface BlockSection {
  id: string;
  color: string;
  type: SectionType;
  requestedWidth: number;
  requestedHeight: number;
  displayMode: DisplayMode;
  style?: SectionStyle;
}

interface PavingBlock {
  id: string;
  x: number;
  y: number;
  w: number;
  h: number;
  section: BlockSection;
}

interface ActiveEdge {
  orientation: 'V' | 'H';
  coordinate: number;
  affectedA: string[];
  affectedB: string[];
}

interface History {
  past: PavingBlock[][];
  future: PavingBlock[][];
}

// --- Helper: refresh layout positions (collapse gaps between rows) ---
function refreshLayoutPositions(currentBlocks: PavingBlock[]): PavingBlock[] {
  if (currentBlocks.length === 0) return [];
  const sorted = [...currentBlocks].sort((a, b) => a.y - b.y || a.x - b.x);
  const segments: { y: number; h: number; blockIds: string[] }[] = [];
  sorted.forEach(block => {
    const segment = segments.find(s => Math.abs(s.y - block.y) < EPSILON);
    if (segment) {
      segment.blockIds.push(block.id);
      segment.h = Math.max(segment.h, block.h);
    } else {
      segments.push({ y: block.y, h: block.h, blockIds: [block.id] });
    }
  });

  let currentY = 0;
  const updated = [...currentBlocks];
  segments.forEach(seg => {
    seg.blockIds.forEach(id => {
      const bIdx = updated.findIndex(b => b.id === id);
      updated[bIdx] = { ...updated[bIdx], y: currentY, h: seg.h };
    });
    currentY += seg.h;
  });
  return updated;
}

// --- Main Component ---
export function PavingCanvas() {
  const [blocks, setBlocks] = useState<PavingBlock[]>([]);
  const [history, setHistory] = useState<History>({ past: [], future: [] });
  const [selectedBlockIds, setSelectedBlockIds] = useState<string[]>([]);
  const [activeEdge, setActiveEdge] = useState<ActiveEdge | null>(null);
  const [message, setMessage] = useState<string | null>(null);
  const containerRef = useRef<HTMLDivElement>(null);
  
  const setStoreSelectedBlock = useEditorStore((s) => s.setSelectedBlock);
  const setGridBlocks = useEditorStore((s) => s.setGridBlocks);
  const storeGridBlocks = useEditorStore((s) => s.gridBlocks);
  const storeSections = useEditorStore((s) => s.pageConfig.sections);
  const isLayoutEditing = useEditorStore((s) => s.isLayoutEditing);

  const blocksRef = useRef<PavingBlock[]>(blocks);
  blocksRef.current = blocks;
  const localBlockIdsRef = useRef<Set<string>>(new Set());
  localBlockIdsRef.current = new Set(blocks.map(b => b.id));

  // Sync local blocks to store so assignSectionToBlock can match by ID
  const syncToStore = (currentBlocks: PavingBlock[]) => {
    setGridBlocks(currentBlocks.map(b => ({
      id: b.id,
      sectionId: b.section.id !== 'S0' ? b.section.id : undefined,
      row: 0,
      col: 0,
      bounds: { top: b.y, left: b.x, right: b.x + b.w, bottom: b.y + b.h },
      displayMode: b.section.displayMode,
    })));
  };

  // After every blocks change, sync positions to store
  useEffect(() => {
    if (blocks.length > 0) {
      syncToStore(blocks);
    }
  }, [blocks]);

  // Watch for store gridBlocks section changes (from sidebar assignment)
  useEffect(() => {
    setBlocks(prev => {
      let changed = false;
      const next: PavingBlock[] = prev.map(b => {
        const gb = storeGridBlocks.find(g => g.id === b.id);
        if (gb?.sectionId && gb.sectionId !== b.section.id) {
          changed = true;
          const section = storeSections.find(s => s.id === gb.sectionId);
          const libItem = SECTION_LIBRARY.find(item => item.type === section?.type);
          return {
            ...b,
            section: {
              ...b.section,
              id: gb.sectionId,
              color: libItem?.color || '#3b82f6',
              displayMode: 'LOCKED' as DisplayMode,
              requestedWidth: (section?.content as any)?.requestedWidth || 0,
              requestedHeight: (section?.content as any)?.requestedHeight || 0,
              style: section?.style || {},
            },
          };
        }
        if (gb && !gb.sectionId && b.section.id !== 'S0') {
          changed = true;
          return {
            ...b,
            section: { ...b.section, id: 'S0', color: '#1e293b', type: 'ADAPTIVE' as SectionType, displayMode: 'UNLOCKED' as DisplayMode, style: {} },
          };
        }
        return b;
      });
      return changed ? next : prev;
    });
  }, [storeGridBlocks, storeSections]);

  // Re-initialize from store gridBlocks when a custom layout is loaded (IDs don't match local)
  useEffect(() => {
    if (storeGridBlocks.length > 0) {
      const storeIds = new Set(storeGridBlocks.map(gb => gb.id));
      const anyMatch = [...storeIds].some(id => localBlockIdsRef.current.has(id));
      if (!anyMatch && localBlockIdsRef.current.size > 0) {
        setBlocks(storeGridBlocks.map(gb => {
          const section = gb.sectionId ? storeSections.find(s => s.id === gb.sectionId) : null;
          const sectionType: SectionType = section ? section.type : 'ADAPTIVE';
          const libItem = section ? SECTION_LIBRARY.find(item => item.type === sectionType) : null;
          return {
            id: gb.id,
            x: gb.bounds.left,
            y: gb.bounds.top,
            w: gb.bounds.right - gb.bounds.left,
            h: gb.bounds.bottom - gb.bounds.top,
            section: {
              id: gb.sectionId || 'S0',
              color: section ? libItem?.color || '#3b82f6' : '#1e293b',
              type: sectionType,
              requestedWidth: section ? (section.content as any)?.requestedWidth || 0 : 0,
              requestedHeight: section ? (section.content as any)?.requestedHeight || 0 : 0,
              displayMode: (gb.sectionId ? 'LOCKED' : 'UNLOCKED') as DisplayMode,
              style: section?.style || {},
            },
          };
        }));
      }
    }
  }, [storeGridBlocks, storeSections]);

  const getSectionName = (block: PavingBlock): string | null => {
    const gb = storeGridBlocks.find(g => g.id === block.id);
    if (gb?.sectionId) {
      const section = storeSections.find(s => s.id === gb.sectionId);
      if (section) {
        const info = SECTION_TYPES.find(st => st.type === section.type);
        return info ? `${info.icon} ${info.label}` : section.type;
      }
    }
    return null;
  };


  // Initialize 4 equal rows on mount
  useEffect(() => {
    const initialH = TARGET_VIEW_HEIGHT / 4;
    const init: PavingBlock[] = Array.from({ length: 4 }).map((_, i) => ({
      id: generateBlockId(),
      x: 0,
      y: i * initialH,
      w: FRAME_WIDTH,
      h: initialH,
      section: {
        id: 'S0',
        color: '#1e293b',
        type: 'ADAPTIVE',
        requestedWidth: 200,
        requestedHeight: 150,
        displayMode: 'UNLOCKED',
      },
    }));
    setBlocks(init);
  }, []);

  // --- History ---
  const saveHistory = (currentBlocks: PavingBlock[]) => {
    setHistory(prev => ({ past: [...prev.past, currentBlocks], future: [] }));
  };

  const undo = () => {
    if (history.past.length === 0) return;
    const previous = history.past[history.past.length - 1];
    setHistory({ past: history.past.slice(0, -1), future: [blocks, ...history.future] });
    setBlocks(previous);
    setSelectedBlockIds([]);
  };

  const redo = () => {
    if (history.future.length === 0) return;
    const next = history.future[0];
    setHistory({ past: [...history.past, blocks], future: history.future.slice(1) });
    setBlocks(next);
    setSelectedBlockIds([]);
  };

  // --- Split Vertical (left/right) ---
  const handleSplitV = (id: string) => {
    const idx = blocks.findIndex(b => b.id === id);
    const target = blocks[idx];
    if (target.w < MIN_SIZE * 2) {
      setMessage(`Block too narrow to split (min ${MIN_SIZE}px)`);
      setTimeout(() => setMessage(null), 2000);
      return;
    }
    saveHistory(blocks);
    const halfW = Math.round(target.w / 2);
    const newBlock: PavingBlock = {
      ...target,
      id: generateBlockId(),
      x: target.x + halfW,
      w: target.w - halfW,
      section: { ...target.section, id: 'S0', color: '#1e293b', type: 'ADAPTIVE', displayMode: 'UNLOCKED' },
    };
    const updated = [...blocks];
    updated[idx] = { ...target, w: halfW };
    updated.splice(idx + 1, 0, newBlock);
    setBlocks(updated);
  };

  // --- Split Horizontal (top/bottom) ---
  const handleSplitH = (id: string) => {
    const idx = blocks.findIndex(b => b.id === id);
    const target = blocks[idx];
    if (target.h < MIN_SIZE * 2) {
      setMessage(`Block too short to split (min ${MIN_SIZE}px)`);
      setTimeout(() => setMessage(null), 2000);
      return;
    }
    saveHistory(blocks);
    const halfH = Math.round(target.h / 2);
    const newBlock: PavingBlock = {
      ...target,
      id: generateBlockId(),
      y: target.y + halfH,
      h: target.h - halfH,
      section: { ...target.section, id: 'S0', color: '#1e293b', type: 'ADAPTIVE', displayMode: 'UNLOCKED' },
    };
    const updated = [...blocks];
    updated[idx] = { ...target, h: halfH };
    updated.splice(idx + 1, 0, newBlock);
    setBlocks(updated);
  };

  // --- Merge two selected blocks ---
  const handleMerge = () => {
    if (selectedBlockIds.length !== 2) return;
    const b1 = blocks.find(b => b.id === selectedBlockIds[0])!;
    const b2 = blocks.find(b => b.id === selectedBlockIds[1])!;
    const touchX = Math.abs(b1.x + b1.w - b2.x) < EPSILON || Math.abs(b2.x + b2.w - b1.x) < EPSILON;
    const touchY = Math.abs(b1.y + b1.h - b2.y) < EPSILON || Math.abs(b2.y + b2.h - b1.y) < EPSILON;
    const overlapY = Math.max(b1.y, b2.y) < Math.min(b1.y + b1.h, b2.y + b2.h);
    const overlapX = Math.max(b1.x, b2.x) < Math.min(b1.x + b1.w, b2.x + b2.w);
    const adjacent = (touchX && overlapY) || (touchY && overlapX);
    const newX = Math.min(b1.x, b2.x), newY = Math.min(b1.y, b2.y);
    const newW = Math.max(b1.x + b1.w, b2.x + b2.w) - newX, newH = Math.max(b1.y + b1.h, b2.y + b2.h) - newY;
    const areaSum = (b1.w * b1.h) + (b2.w * b2.h);
    if (!adjacent || Math.abs(areaSum - (newW * newH)) > 10) {
      setMessage('Merge failed: Blocks must form a perfect rectangle.');
      setTimeout(() => setMessage(null), 2000);
      return;
    }
    saveHistory(blocks);
    const merged: PavingBlock = {
      id: generateBlockId(),
      x: newX,
      y: newY,
      w: newW,
      h: newH,
      section: { ...b1.section },
    };
    setBlocks(refreshLayoutPositions([...blocks.filter(b => !selectedBlockIds.includes(b.id)), merged]));
    setSelectedBlockIds([]);
  };

  // --- Edge drag: mousedown ---
  const onMouseDown = (e: React.MouseEvent) => {
    if (!containerRef.current) return;
    const rect = containerRef.current.getBoundingClientRect();
    const mx = e.clientX - rect.left, my = e.clientY - rect.top;
    for (const b of blocks) {
      // Check vertical edges (right side of blocks)
      if (Math.abs(mx - (b.x + b.w)) < BORDER_HIT_AREA && my >= b.y && my <= b.y + b.h && b.x + b.w < FRAME_WIDTH) {
        saveHistory(blocks);
        setActiveEdge({
          orientation: 'V',
          coordinate: b.x + b.w,
          affectedA: blocks.filter(bl => Math.abs(bl.x + bl.w - (b.x + b.w)) < EPSILON).map(bl => bl.id),
          affectedB: blocks.filter(bl => Math.abs(bl.x - (b.x + b.w)) < EPSILON).map(bl => bl.id),
        });
        return;
      }
      // Check horizontal edges (bottom side of blocks)
      if (Math.abs(my - (b.y + b.h)) < BORDER_HIT_AREA && mx >= b.x && mx <= b.x + b.w) {
        saveHistory(blocks);
        setActiveEdge({
          orientation: 'H',
          coordinate: b.y + b.h,
          affectedA: blocks.filter(bl => Math.abs(bl.y + bl.h - (b.y + b.h)) < EPSILON).map(bl => bl.id),
          affectedB: blocks.filter(bl => Math.abs(bl.y - (b.y + b.h)) < EPSILON).map(bl => bl.id),
        });
        return;
      }
    }
  };

  // --- Edge drag: mousemove ---
  const onMouseMove = (e: React.MouseEvent) => {
    if (!activeEdge || !containerRef.current) return;
    const rect = containerRef.current.getBoundingClientRect();
    const rawPos = activeEdge.orientation === 'V' ? e.clientX - rect.left : e.clientY - rect.top;

    let pos = rawPos;

    // Sticky Alignment: snap to existing boundaries
    const snapPoints = new Set<number>();
    if (activeEdge.orientation === 'V') {
      snapPoints.add(0);
      snapPoints.add(FRAME_WIDTH);
      blocks.forEach(b => {
        snapPoints.add(b.x);
        snapPoints.add(b.x + b.w);
      });
    } else {
      snapPoints.add(0);
      blocks.forEach(b => {
        snapPoints.add(b.y);
        snapPoints.add(b.y + b.h);
      });
    }

    for (const point of snapPoints) {
      if (Math.abs(pos - point) < SNAP_THRESHOLD) {
        pos = point;
        break;
      }
    }

    // Constraints & Clamping
    const initialCoord = activeEdge.coordinate;
    const checkClamping = (blockIds: string[], type: 'A' | 'B') => {
      for (const id of blockIds) {
        const b = blocks.find(x => x.id === id);
        if (!b) continue;
        let newDim: number;
        if (type === 'A') {
          newDim = (activeEdge.orientation === 'V' ? b.w : b.h) + (pos - initialCoord);
        } else {
          newDim = (activeEdge.orientation === 'V' ? b.w : b.h) - (pos - initialCoord);
        }

        if (newDim < MIN_SIZE && newDim > DELETE_THRESHOLD) {
          const limit = type === 'A'
            ? (activeEdge.orientation === 'V' ? b.x + MIN_SIZE : b.y + MIN_SIZE)
            : (activeEdge.orientation === 'V' ? (b.x + b.w) - MIN_SIZE : (b.y + b.h) - MIN_SIZE);
          pos = limit;
        } else if (newDim <= DELETE_THRESHOLD) {
          const limit = type === 'A'
            ? (activeEdge.orientation === 'V' ? b.x : b.y)
            : (activeEdge.orientation === 'V' ? b.x + b.w : b.y + b.h);
          pos = limit;
        }
      }
    };

    checkClamping(activeEdge.affectedA, 'A');
    checkClamping(activeEdge.affectedB, 'B');

    const delta = pos - activeEdge.coordinate;
    setBlocks(prev => {
      const next = prev.map(b => {
        if (activeEdge.affectedA.includes(b.id)) {
          return activeEdge.orientation === 'V' ? { ...b, w: b.w + delta } : { ...b, h: b.h + delta };
        }
        if (activeEdge.affectedB.includes(b.id)) {
          return activeEdge.orientation === 'V' ? { ...b, x: b.x + delta, w: b.w - delta } : { ...b, y: b.y + delta, h: b.h - delta };
        }
        return b;
      });
      const kept = next.filter(b => b.w > 2 && b.h > 2);
      return kept.length !== next.length ? refreshLayoutPositions(kept) : next;
    });
    setActiveEdge(prev => prev ? { ...prev, coordinate: pos } : null);

    // Auto-scroll when dragging downwards
    if (activeEdge.orientation === 'H' && containerRef.current.parentElement) {
      const wrapper = containerRef.current.parentElement;
      const scrollBottom = wrapper.scrollTop + wrapper.clientHeight;
      if (pos > scrollBottom - 50) {
        wrapper.scrollTop = pos - wrapper.clientHeight + 100;
      }
    }
  };

  const canvasHeight = Math.max(TARGET_VIEW_HEIGHT, 0, ...blocks.map(b => b.y + b.h)) + 100;

  return (
    <div className="paving-engine">
      {/* Toast */}
      {message && (
        <div className="paving-toast">
          <Info size={18} /> {message}
        </div>
      )}

      <div className="paving-body">
        <div className="paving-canvas-wrapper" style={{ overflowY: 'auto' }}>
          <div
            ref={containerRef}
            onMouseDown={onMouseDown}
            onMouseMove={onMouseMove}
            onMouseUp={() => setActiveEdge(null)}
            onMouseLeave={() => setActiveEdge(null)}
            className="paving-canvas"
            style={{
              width: FRAME_WIDTH,
              minWidth: FRAME_WIDTH,
              height: canvasHeight,
              cursor: activeEdge ? (activeEdge.orientation === 'V' ? 'col-resize' : 'row-resize') : 'default',
            }}
          >
            {blocks.map(block => {
              const isLocked = block.section.id !== 'S0' && block.section.displayMode === 'LOCKED';
              return (
                <div
                  key={block.id}
                  onClick={() => {
                    const isSelected = selectedBlockIds.includes(block.id);
                    const newIds = isSelected ? selectedBlockIds.filter(i => i !== block.id) : [...selectedBlockIds, block.id];
                    setSelectedBlockIds(newIds);
                    setStoreSelectedBlock(newIds.length === 1 ? block.id : null);
                  }}
                  onDragOver={(e) => e.preventDefault()}
                  onDrop={(e) => {
                    e.preventDefault();
                    const libSection = JSON.parse(e.dataTransfer.getData('section'));
                    saveHistory(blocks);
                    setBlocks(prev => prev.map(b => b.id === block.id ? {
                      ...b,
                      section: {
                        id: libSection.id,
                        color: libSection.color,
                        type: libSection.type,
                        requestedWidth: libSection.rW,
                        requestedHeight: libSection.rH,
                        displayMode: libSection.id === 'S0' ? 'UNLOCKED' : 'LOCKED',
                      },
                    } : b));
                  }}
                  className={`paving-block ${selectedBlockIds.includes(block.id) ? 'selected' : ''}`}
                  style={{ left: block.x, top: block.y, width: block.w, height: block.h }}
                >
                  {block.section.id !== 'S0' && (
                    <button
                      onClick={(e) => {
                        e.stopPropagation();
                        saveHistory(blocks);
                        setBlocks(prev => prev.map(b => b.id === block.id
                          ? { ...b, section: { ...b.section, displayMode: isLocked ? 'UNLOCKED' : 'LOCKED' } }
                          : b
                        ));
                      }}
                      className="paving-lock-btn"
                    >
                      {isLocked ? <Lock size={12} className="text-lock" /> : <Unlock size={12} className="text-unlock" />}
                    </button>
                  )}

                  <div className="paving-block-inner">
                    <div
                      className="paving-block-fill"
                      data-default={block.section.id === 'S0'}
                      style={
                        block.section.id === 'S0'
                          ? { width: '100%', height: '100%', backgroundColor: '#f1f5f9' }
                          : isLocked
                            ? {
                                width: block.section.requestedWidth,
                                height: block.section.requestedHeight,
                                backgroundColor: block.section.color,
                                backgroundImage: block.section.style?.backgroundImage || undefined,
                                backgroundSize: block.section.style?.backgroundImage ? 'cover' : undefined,
                                backgroundPosition: block.section.style?.backgroundImage ? 'center' : undefined,
                                borderRadius: '4px',
                                flexShrink: 0,
                              }
                            : { width: '100%', height: '100%', backgroundColor: block.section.color }
                      }
                    >
                      <div className="paving-block-label-wrapper">
                        <span className="paving-block-label">
                          {block.section.id === 'S0' ? '' : block.section.id}
                        </span>
                        {getSectionName(block) && (
                          <span className="paving-block-section-name">{getSectionName(block)}</span>
                        )}
                      </div>
                    </div>

                    <div className="paving-block-overlay">
                      <button onClick={(e) => { e.stopPropagation(); handleSplitV(block.id); }} className="paving-split-btn">
                        <Scissors size={14} className="paving-icon-rotated" />
                      </button>
                      <button onClick={(e) => { e.stopPropagation(); handleSplitH(block.id); }} className="paving-split-btn">
                        <Scissors size={14} />
                      </button>
                    </div>
                  </div>
                </div>
              );
            })}

            {/* Bottom resize handle for extending canvas */}
            {isLayoutEditing && (
              <div
                onMouseDown={(e) => {
                  e.stopPropagation();
                  saveHistory(blocks);
                  const lastBlock = [...blocks].sort((a, b) => (b.y + b.h) - (a.y + b.h))[0];
                  if (!lastBlock || !containerRef.current) return;
                  setActiveEdge({
                    orientation: 'H',
                    coordinate: lastBlock.y + lastBlock.h,
                    affectedA: [lastBlock.id],
                    affectedB: [],
                  });
                }}
                style={{
                  position: 'absolute',
                  left: 0,
                  right: 0,
                  bottom: 0,
                  height: '24px',
                  cursor: 'row-resize',
                  zIndex: 10,
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'center',
                }}
              >
                <div style={{
                  width: '60px',
                  height: '4px',
                  background: '#cbd5e1',
                  borderRadius: '2px',
                  transition: 'background 0.15s',
                }} />
              </div>
            )}
          </div>
        </div>

        {/* Small right sidebar with undo/redo/merge - only show when editing layout */}
        {isLayoutEditing && (
        <div className="paving-toolbar-sidebar">
          <div className="paving-toolbar-group">
            <button
              onClick={undo}
              disabled={history.past.length === 0}
              title="Undo"
              className={`paving-toolbar-btn ${history.past.length > 0 ? 'active' : ''}`}
            >
              <Undo2 size={18} />
            </button>
            <button
              onClick={redo}
              disabled={history.future.length === 0}
              title="Redo"
              className={`paving-toolbar-btn ${history.future.length > 0 ? 'active' : ''}`}
            >
              <Redo2 size={18} />
            </button>
          </div>
          <button
            onClick={handleMerge}
            disabled={selectedBlockIds.length !== 2}
            title="Merge selected blocks"
            className={`paving-toolbar-btn merge ${selectedBlockIds.length === 2 ? 'ready' : ''}`}
          >
            <Merge size={18} />
          </button>
        </div>
        )}
      </div>
    </div>
  );
}
