// src/saas/features/listing-editor/components/section-renderer.component.ts
import { Component, input, computed, ChangeDetectionStrategy } from '@angular/core';
import { CommonModule } from '@angular/common';
import type { Section, Theme, SectionStyle } from '../models/paving.types';
import { SECTION_TYPES } from '../constants/paving.constants';

@Component({
  selector: 'app-section-renderer',
  standalone: true,
  imports: [CommonModule],
  template: `
    <div
      class="section-renderer"
      [style]="sectionStyle()"
      [class.section-animate-fade-in]="animationClass() === 'fade-in'"
      [class.section-animate-fade-up]="animationClass() === 'fade-up'"
      [class.section-animate-slide]="animationClass() === 'slide'"
      (mouseenter)="onMouseEnter($event)"
      (mouseleave)="onMouseLeave($event)">

      @if (blockId()) {
        <div class="section-label-badge">{{ sectionInfo()?.label }}</div>
      }

      <div class="section-content-wrapper">
        @switch (section().type) {
          @case ('hero') {
            <div class="section-hero" [class.text-left]="section().style.textAlign === 'left'" [class.text-center]="!section().style.textAlign || section().style.textAlign === 'center'" [class.text-right]="section().style.textAlign === 'right'">
              <h1 class="hero-title">{{ section().content['title'] || 'Hero Title' }}</h1>
              @if (section().content['subtitle']) {
                <p class="hero-subtitle">{{ section().content['subtitle'] }}</p>
              }
              @if (section().content['ctaText']) {
                <button class="hero-cta">{{ section().content['ctaText'] }}</button>
              }
            </div>
          }
          @case ('description') {
            <div class="section-description">
              <h2 class="section-heading">{{ section().content['title'] || 'Description' }}</h2>
              <div class="description-content" [innerHTML]="section().content['body'] || section().content['content'] || '<p>Click to edit description...</p>'"></div>
            </div>
          }
          @case ('contact') {
            <div class="section-contact">
              <h2 class="section-heading">Contact</h2>
              <div class="contact-details">
                <div>📧 {{ section().content['email'] || 'email@example.com' }}</div>
                @if (section().content['phone']) {
                  <div>📞 {{ section().content['phone'] }}</div>
                }
                @if (section().content['address']) {
                  <div>📍 {{ section().content['address'] }}</div>
                }
              </div>
            </div>
          }
          @case ('price') {
            <div class="section-price">
              <div class="price-amount">{{ section().content['minPrice'] || 0 }} {{ section().content['currency'] || '€' }}</div>
              <div class="price-period">/ {{ section().content['period'] || 'night' }}</div>
            </div>
          }
          @case ('characteristics') {
            <div class="section-characteristics">
              <h2 class="section-heading">Property Details</h2>
              <div class="characteristics-grid">
                <div class="characteristic-item">
                  <div class="char-icon">📐</div>
                  <div class="char-value">{{ section().content['sqm'] || 0 }} m²</div>
                </div>
                <div class="characteristic-item">
                  <div class="char-icon">🚪</div>
                  <div class="char-value">{{ section().content['rooms'] || 0 }} rooms</div>
                </div>
                <div class="characteristic-item">
                  <div class="char-icon">🛏️</div>
                  <div class="char-value">{{ section().content['beds'] || 0 }} beds</div>
                </div>
                <div class="characteristic-item">
                  <div class="char-icon">🚿</div>
                  <div class="char-value">{{ section().content['bathrooms'] || 0 }} baths</div>
                </div>
                <div class="characteristic-item">
                  <div class="char-icon">👥</div>
                  <div class="char-value">{{ section().content['guests'] || 0 }} guests</div>
                </div>
              </div>
            </div>
          }
          @case ('photos') {
            <div class="section-photos">
              <h2 class="section-heading">Photo Gallery</h2>
              @if (photoList().length > 0) {
                <div class="photos-grid">
                  @for (img of photoList().slice(0, 9); track $index) {
                    <div class="photo-item">
                      <img [src]="img.url" [alt]="img.caption || ''" class="photo-img" />
                    </div>
                  }
                </div>
              } @else {
                <div class="empty-state">No photos available</div>
              }
            </div>
          }
          @case ('amenities') {
            <div class="section-amenities">
              <h2 class="section-heading">{{ section().content['title'] || 'Amenities' }}</h2>
              @if (getContentArray('list').length > 0) {
                <div class="amenities-list two-column">
                  @for (item of getContentArray('list'); track $index) {
                    <div class="amenity-item">✓ {{ item }}</div>
                  }
                </div>
              } @else {
                <div class="empty-state">Click to configure amenities...</div>
              }
            </div>
          }
          @case ('map') {
            <div class="section-map">
              <h2 class="section-heading">Location</h2>
              <div class="map-placeholder">🗺️ Map placeholder</div>
            </div>
          }
          @case ('header') {
            <div class="section-header">
              <div class="header-logo">{{ section().content['logo'] || 'Logo' }}</div>
              <div class="header-nav">
                <span>Home</span>
                <span>About</span>
                <span>Contact</span>
              </div>
            </div>
          }
          @case ('bottom') {
            <div class="section-bottom">
              <div class="copyright">© {{ section().content['copyright'] || '2026' }}</div>
            </div>
          }
          @case ('closeTo') {
            <div class="section-close-to">
              <h2 class="section-heading">Close To</h2>
              @if (getContentArray('items').length > 0) {
                <div class="close-to-list">
                  @for (item of getContentArray('items'); track $index) {
                    <span class="close-to-chip">📍 {{ item }}</span>
                  }
                </div>
              } @else {
                <div class="empty-state">Click to add nearby places...</div>
              }
            </div>
          }
          @case ('facilities') {
            <div class="section-facilities">
              <h2 class="section-heading">Facilities</h2>
              @if (getContentArray('list').length > 0) {
                <div class="facilities-grid">
                  @for (item of getContentArray('list'); track $index) {
                    <div class="facility-item">✓ {{ item }}</div>
                  }
                </div>
              } @else {
                <div class="empty-state">Click to configure facilities...</div>
              }
            </div>
          }
          @case ('floorPlan') {
            <div class="section-floor-plan">
              <h2 class="section-heading">Floor Plan</h2>
              @if (section().content['image']) {
                <img [src]="section().content['image']" alt="Floor Plan" class="floor-plan-img" />
              } @else {
                <div class="floor-plan-placeholder">📋 Floor Plan placeholder</div>
              }
            </div>
          }
          @case ('rules') {
            <div class="section-rules">
              <h2 class="section-heading">House Rules</h2>
              @if (getContentArray('items').length > 0) {
                <ul class="rules-list">
                  @for (item of getContentArray('items'); track $index) {
                    <li>{{ item }}</li>
                  }
                </ul>
              } @else {
                <div class="empty-state">Click to add house rules...</div>
              }
            </div>
          }
          @case ('testimonials') {
            <div class="section-testimonials">
              <h2 class="section-heading">Testimonials</h2>
              @if (getContentArray('items').length > 0) {
                <div class="testimonials-list">
                  @for (item of getContentArray('items'); track $index) {
                    <div class="testimonial-card">
                      <div class="testimonial-text">{{ getItemField(item, 'text', 'Great stay!') }}</div>
                      <div class="testimonial-author">— {{ getItemField(item, 'author', 'Guest') }}</div>
                    </div>
                  }
                </div>
              } @else {
                <div class="empty-state">Click to add testimonials...</div>
              }
            </div>
          }
          @case ('location') {
            <div class="section-location">
              <h2 class="section-heading">Location</h2>
              <p class="location-description">{{ section().content['description'] || 'Click to add location description...' }}</p>
            </div>
          }
          @case ('recap') {
            <div class="section-recap">
              <h2 class="section-heading">Booking Details</h2>
              <div class="recap-grid">
                <div><strong>Check-in:</strong> {{ section().content['checkIn'] || '15:00' }}</div>
                <div><strong>Check-out:</strong> {{ section().content['checkOut'] || '11:00' }}</div>
                <div><strong>Min nights:</strong> {{ section().content['minNights'] || 1 }}</div>
                <div><strong>Cancellation:</strong> {{ section().content['cancellationPolicy'] || 'Flexible' }}</div>
              </div>
            </div>
          }
          @case ('otherProperties') {
            <div class="section-other-properties">
              <h2 class="section-heading">Other Properties</h2>
              <div class="empty-state">Click to configure...</div>
            </div>
          }
          @default {
            <div class="section-placeholder">
              {{ sectionInfo()?.icon }} {{ sectionInfo()?.label }}
            </div>
          }
        }
      </div>
    </div>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class SectionRendererComponent {
  section = input.required<Section>();
  blockId = input<string | undefined>(undefined);
  theme = input<Theme | undefined>(undefined);
  blockStyle = input<Partial<SectionStyle> | undefined>(undefined);

  sectionInfo = computed(() => SECTION_TYPES.find(s => s.type === this.section().type));

  mergedStyle = computed(() => {
    const s = this.section();
    const bs = this.blockStyle();
    return { ...s.style, ...bs };
  });

  animationClass = computed(() => {
    const scroll = this.section().animations?.scroll;
    switch (scroll) {
      case 'fade-in': return 'fade-in';
      case 'fade-up': return 'fade-up';
      case 'slide': return 'slide';
      default: return '';
    }
  });

  sectionStyle = computed(() => {
    const ms = this.mergedStyle();
    const theme = this.theme();
    const bgImage = ms.backgroundImage;
    const hasBgImage = !!bgImage;
    const isParallax = ms.backgroundAttachment === 'parallax' && !!bgImage;

    return {
      position: 'relative' as const,
      border: 'none',
      margin: 0,
      borderRadius: 0,
      cursor: 'pointer',
      transition: 'border-color 0.15s ease',
      backgroundColor: ms.backgroundColor || (hasBgImage ? 'transparent' : theme?.colors.background || 'transparent'),
      backgroundImage: hasBgImage ? bgImage : undefined,
      backgroundSize: isParallax ? 'cover' : 'contain' as const,
      backgroundPosition: isParallax ? 'top left' as const : 'center' as const,
      backgroundRepeat: 'no-repeat' as const,
      backgroundAttachment: isParallax ? 'fixed' as const : 'scroll' as const,
      overflow: 'hidden' as const,
      flex: 1,
      width: '100%',
      height: '100%',
      padding: isParallax ? '0' : (ms.padding || theme?.spacing.sectionPadding || '0'),
      textAlign: ms.textAlign || 'left',
      fontFamily: theme?.typography.bodyFont || 'inherit',
      color: ms.color || theme?.colors.text || 'inherit',
    };
  });

  photoList = computed(() => {
    const c = this.section().content;
    const images = c['images'];
    const photos = c['photos'] || [];
    if (Array.isArray(images) && images.length > 0) return images;
    if (Array.isArray(photos) && photos.length > 0) return photos;
    return [];
  });

  getContentArray(key: string): unknown[] {
    const val = this.section()?.content?.[key];
    return Array.isArray(val) ? val : [];
  }

  getItemField(item: unknown, field: string, fallback: string): string {
    if (typeof item === 'object' && item !== null) {
      const val = (item as Record<string, unknown>)[field];
      return typeof val === 'string' ? val : fallback;
    }
    return fallback;
  }

  onMouseEnter(event: MouseEvent): void {
    const target = event.currentTarget as HTMLElement;
    const hover = this.section().animations?.hover;
    switch (hover) {
      case 'zoom':
        target.style.transform = 'scale(1.02)';
        break;
      case 'lift':
        target.style.transform = 'translateY(-4px)';
        target.style.boxShadow = '0 8px 25px rgba(0,0,0,0.1)';
        break;
      case 'glow':
        target.style.boxShadow = '0 0 20px rgba(59, 130, 246, 0.3)';
        break;
    }
  }

  onMouseLeave(event: MouseEvent): void {
    const target = event.currentTarget as HTMLElement;
    target.style.transform = '';
    target.style.boxShadow = '';
  }
}

// src/listing-editor/components/SectionRenderer.tsx
import type { Section, SectionType, Theme } from '../types';
import { useEditorStore } from '../store/useEditorStore';
import { SECTION_TYPES } from '../lib/constants';

interface SectionRendererProps {
  section: Section;
  style?: React.CSSProperties;
  theme?: Theme;
  blockId?: string;
}

export function SectionRenderer({ section, style: layoutStyle, theme, blockId }: SectionRendererProps) {
  const selectedBlockId = useEditorStore((s) => s.selectedBlockId);
  const setSelectedSection = useEditorStore((s) => s.setSelectedSection);
  const setSelectedBlock = useEditorStore((s) => s.setSelectedBlock);
  const splitBlock = useEditorStore((s) => s.splitBlock);

  const photos = useEditorStore((s) => s.photos);

  const isSelectedBlock = selectedBlockId === blockId;
  const sectionInfo = SECTION_TYPES.find((s) => s.type === section.type);

  const handleClick = (e: React.MouseEvent) => {
    e.stopPropagation();
    if (blockId) {
      setSelectedBlock(blockId);
    }
    setSelectedSection(section.id);
  };

  const handleDoubleClick = (e: React.MouseEvent) => {
    e.stopPropagation();
    if (blockId) {
      splitBlock(blockId, 'vertical');
    }
  };

  const bgImage = section.style?.backgroundImage;
  const hasBgImage = !!bgImage;
  const isParallax = section.style?.backgroundAttachment === 'parallax' && bgImage;

  const sectionStyle: React.CSSProperties = {
    ...layoutStyle,
    position: 'relative',
    border: 'none',
    margin: 0,
    borderRadius: 0,
    cursor: 'pointer',
    transition: 'border-color 0.15s ease',
    backgroundColor: section.style.backgroundColor || (hasBgImage ? 'transparent' : theme?.colors.background || 'transparent'),
    backgroundImage: hasBgImage ? bgImage : undefined,
    backgroundSize: isParallax ? 'cover' : 'contain',
    backgroundPosition: isParallax ? 'top left' : 'center',
    backgroundRepeat: 'no-repeat',
    backgroundAttachment: isParallax ? 'fixed' : 'scroll',
    overflow: 'hidden',
    flex: 1,
    padding: isParallax ? '0' : (section.style.padding || theme?.spacing.sectionPadding || '0'),
    textAlign: section.style.textAlign || 'left',
    fontFamily: theme?.typography.bodyFont || 'inherit',
    color: section.style.color || theme?.colors.text || 'inherit',
  };

  const animationClass = (() => {
    switch (section.animations?.scroll) {
      case 'fade-in':
        return 'section-animate-fade-in';
      case 'fade-up':
        return 'section-animate-fade-up';
      case 'slide':
        return 'section-animate-slide';
      default:
        return '';
    }
  })();

  const handleMouseEnter = (e: React.MouseEvent<HTMLDivElement>) => {
    const target = e.currentTarget;
    switch (section.animations?.hover) {
      case 'zoom':
        target.style.transform = 'scale(1.02)';
        break;
      case 'lift':
        target.style.transform = 'translateY(-4px)';
        target.style.boxShadow = '0 8px 25px rgba(0,0,0,0.1)';
        break;
      case 'glow':
        target.style.boxShadow = '0 0 20px rgba(59, 130, 246, 0.3)';
        break;
    }
  };

  const handleMouseLeave = (e: React.MouseEvent<HTMLDivElement>) => {
    const target = e.currentTarget;
    target.style.transform = '';
    target.style.boxShadow = '';
  };

return (
    <div
      onClick={handleClick}
      onDoubleClick={handleDoubleClick}
      onMouseEnter={handleMouseEnter}
      onMouseLeave={handleMouseLeave}
      style={{...sectionStyle, minHeight: 0}}
      className={`section-${section.id} ${animationClass}`}
    >
      {isSelectedBlock && (
        <div
          style={{
            position: 'absolute',
            top: '-10px',
            right: '12px',
            background: '#3b82f6',
            color: '#fff',
            fontSize: '11px',
            padding: '2px 8px',
            borderRadius: '4px',
            zIndex: 1,
          }}
        >
          {sectionInfo?.label}
        </div>
      )}

      <div style={{ position: 'relative', zIndex: 1, height: '100%', overflow: isParallax ? 'auto' : undefined }}>
        <SectionContent type={section.type} content={section.content} sectionInfo={sectionInfo} theme={theme} textAlign={section.style.textAlign} textColor={section.style.color} photos={photos} />
      </div>
    </div>
  );
}

function SectionContent({ type, content, sectionInfo, theme, textAlign, textColor, photos }: { type: SectionType; content: Record<string, unknown>; sectionInfo: { label: string; icon: string } | undefined; theme?: Theme; textAlign?: string; textColor?: string; photos?: { url: string; category?: string }[] }) {
  const c = content as Record<string, string | number | undefined>;
  const activeTextColor = textColor || theme?.colors.text || '#1a202c';
  const primary = textColor || theme?.colors.primary || '#1a365d';
  const text = activeTextColor;
  const textMuted = textColor || theme?.colors.textMuted || '#64748b';
  const headingFont = theme?.typography.headingFont || 'inherit';
  const bodyFont = theme?.typography.bodyFont || 'inherit';

  switch (type) {
    case 'hero':
      return (
        <div
          style={{
            minHeight: 0,
            height: '100%',
            overflow: 'hidden',
            display: 'flex',
            flexDirection: 'column',
            alignItems: textAlign === 'left' ? 'flex-start' : textAlign === 'right' ? 'flex-end' : 'center',
            justifyContent: 'center',
            padding: '12px',
            boxSizing: 'border-box',
            gap: '4px',
          }}
        >
          <h1 style={{ margin: 0, fontSize: 'clamp(14px, 3vw, 24px)', color: primary, fontFamily: headingFont, lineHeight: 1.2, flexShrink: 1 }}>
            {c.title as string || 'Hero Title'}
          </h1>
          {c.subtitle && (
            <p style={{ margin: 0, color: textMuted, fontSize: 'clamp(11px, 2.5vw, 14px)', lineHeight: 1.3, flexShrink: 1 }}>
              {c.subtitle as string}
            </p>
          )}
          {c.ctaText && (
            <button style={{ padding: '6px 12px', background: '#3b82f6', color: '#fff', border: 'none', borderRadius: '6px', cursor: 'pointer', fontSize: '12px', marginTop: '4px', flexShrink: 0 }}>
              {c.ctaText as string}
            </button>
          )}
        </div>
      );

    case 'description':
      return (
        <div style={{ padding: '24px', fontFamily: bodyFont }}>
          <h2 style={{ margin: '0 0 12px', fontSize: '18px', fontFamily: headingFont, color: primary }}>{c.title as string || 'Description'}</h2>
          <div
            style={{ color: text, fontSize: '14px', lineHeight: 1.6 }}
            dangerouslySetInnerHTML={{ __html: c.body as string || '<p>Click to edit description...</p>' }}
          />
        </div>
      );

    case 'contact':
      return (
        <div style={{ padding: '24px', fontFamily: bodyFont }}>
          <h2 style={{ margin: '0 0 16px', fontSize: '18px', fontFamily: headingFont, color: primary }}>Contact</h2>
          <div style={{ fontSize: '14px', color: textMuted }}>
            {c.email ? `📧 ${c.email}` : '📧 email@example.com'}
            {c.phone && <div>📞 {c.phone}</div>}
          </div>
        </div>
      );

    case 'price':
      return (
        <div style={{ padding: '24px', fontFamily: bodyFont }}>
          <div style={{ fontSize: '32px', fontWeight: 700, color: primary }}>
            {c.minPrice || 0} {c.currency || '€'}
            <span style={{ fontSize: '14px', fontWeight: 400, color: textMuted }}> / {c.period || 'night'}</span>
          </div>
        </div>
      );

    case 'characteristics':
      return (
        <div style={{ padding: '24px', fontFamily: bodyFont }}>
          <h2 style={{ margin: '0 0 16px', fontSize: '18px', fontFamily: headingFont, color: primary }}>Property Details</h2>
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: '16px' }}>
            <div style={{ textAlign: 'center' }}>
              <div style={{ fontSize: '24px' }}>📐</div>
              <div style={{ fontSize: '14px', color: textMuted }}>{c.sqm || 0} m²</div>
            </div>
            <div style={{ textAlign: 'center' }}>
              <div style={{ fontSize: '24px' }}>🚪</div>
              <div style={{ fontSize: '14px', color: textMuted }}>{c.rooms || 0} rooms</div>
            </div>
            <div style={{ textAlign: 'center' }}>
              <div style={{ fontSize: '24px' }}>🛏️</div>
              <div style={{ fontSize: '14px', color: textMuted }}>{c.beds || 0} beds</div>
            </div>
            <div style={{ textAlign: 'center' }}>
              <div style={{ fontSize: '24px' }}>🚿</div>
              <div style={{ fontSize: '14px', color: '#64748b' }}>{c.bathrooms || 0} baths</div>
            </div>
            <div style={{ textAlign: 'center' }}>
              <div style={{ fontSize: '24px' }}>👥</div>
              <div style={{ fontSize: '14px', color: '#64748b' }}>{c.guests || 0} guests</div>
            </div>
          </div>
        </div>
      );

    case 'photos':
      const photoList = (Array.isArray(c.images) && (c.images as Array<{ url: string }>).length > 0)
        ? c.images
        : (photos || []).map(p => ({ url: p.url, caption: p.category || '' }));
      return (
        <div style={{ padding: '24px' }}>
          <h2 style={{ margin: '0 0 16px', fontSize: '18px' }}>Photo Gallery</h2>
          {photoList.length > 0 ? (
            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: '8px' }}>
              {(photoList as Array<{ url: string; caption?: string }>).slice(0, 9).map((img, i) => (
                <div key={i} style={{ aspectRatio: '4/3', overflow: 'hidden', borderRadius: '6px', background: '#f1f5f9' }}>
                  <img src={img.url} alt={img.caption || ''} style={{ width: '100%', height: '100%', objectFit: 'cover' }} />
                </div>
              ))}
            </div>
          ) : (
            <div style={{ color: '#94a3b8', fontSize: '14px' }}>No photos available</div>
          )}
        </div>
      );

    case 'amenities':
      return (
        <div style={{ padding: '24px', fontFamily: bodyFont }}>
          <h2 style={{ margin: '0 0 16px', fontSize: '18px', fontFamily: headingFont, color: primary }}>{c.title as string || 'Amenities'}</h2>
          {Array.isArray(c.list) && c.list.length > 0 ? (
            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(2, 1fr)', gap: '8px' }}>
              {c.list.map((item, i) => (
                <div key={i} style={{ fontSize: '14px', color: text }}>✓ {item as string}</div>
              ))}
            </div>
          ) : (
            <div style={{ color: textMuted, fontSize: '14px' }}>Click to configure amenities...</div>
          )}
        </div>
      );

    case 'map':
      return (
        <div style={{ padding: '24px' }}>
          <h2 style={{ margin: '0 0 16px', fontSize: '18px' }}>Location</h2>
          <div
            style={{
              height: '200px',
              background: '#e2e8f0',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              borderRadius: '8px',
              color: '#94a3b8',
            }}
          >
            🗺️ Map placeholder
          </div>
        </div>
      );

    case 'header':
      return (
        <div style={{ padding: '16px 24px', borderBottom: '1px solid #e2e8f0' }}>
          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
            <div style={{ fontSize: '20px', fontWeight: 600 }}>{c.logo as string || 'Logo'}</div>
            <div style={{ display: 'flex', gap: '16px', fontSize: '14px', color: '#64748b' }}>
              <span>Home</span>
              <span>About</span>
              <span>Contact</span>
            </div>
          </div>
        </div>
      );

    case 'bottom':
      return (
        <div style={{ padding: '24px', background: '#1e293b', color: '#94a3b8' }}>
          <div style={{ fontSize: '14px' }}>© {c.copyright as string || new Date().getFullYear()}</div>
        </div>
      );

    case 'closeTo':
      return (
        <div style={{ padding: '24px' }}>
          <h2 style={{ margin: '0 0 16px', fontSize: '18px', fontFamily: headingFont, color: primary }}>Close To</h2>
          {Array.isArray(c.items) && c.items.length > 0 ? (
            <div style={{ display: 'flex', gap: '16px', flexWrap: 'wrap' }}>
              {c.items.map((item, i) => (
                <span key={i} style={{ padding: '8px 12px', background: 'rgba(128,128,128,0.1)', borderRadius: '6px', fontSize: '14px', color: text }}>
                  📍 {item as string}
                </span>
              ))}
            </div>
          ) : (
            <div style={{ color: textMuted, fontSize: '14px' }}>Click to add nearby places...</div>
          )}
        </div>
      );

    case 'facilities':
      return (
        <div style={{ padding: '24px' }}>
          <h2 style={{ margin: '0 0 16px', fontSize: '18px' }}>Facilities</h2>
          {Array.isArray(c.list) && c.list.length > 0 ? (
            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: '12px' }}>
              {c.list.map((item, i) => (
                <div key={i} style={{ display: 'flex', alignItems: 'center', gap: '8px', fontSize: '14px' }}>
                  ✓ {item as string}
                </div>
              ))}
            </div>
          ) : (
            <div style={{ color: '#64748b', fontSize: '14px' }}>Click to configure facilities...</div>
          )}
        </div>
      );

    case 'floorPlan':
      return (
        <div style={{ padding: '24px' }}>
          <h2 style={{ margin: '0 0 16px', fontSize: '18px' }}>Floor Plan</h2>
          {c.image ? (
            <img src={c.image as string} alt="Floor Plan" style={{ width: '100%', borderRadius: '8px' }} />
          ) : (
            <div style={{ height: '200px', background: '#e2e8f0', display: 'flex', alignItems: 'center', justifyContent: 'center', borderRadius: '8px', color: '#94a3b8' }}>
              📋 Floor Plan placeholder
            </div>
          )}
        </div>
      );

    case 'rules':
      return (
        <div style={{ padding: '24px' }}>
          <h2 style={{ margin: '0 0 16px', fontSize: '18px', fontFamily: headingFont, color: primary }}>House Rules</h2>
          {Array.isArray(c.items) && c.items.length > 0 ? (
            <ul style={{ paddingLeft: '20px', color: text, fontSize: '14px' }}>
              {c.items.map((item, i) => (
                <li key={i} style={{ marginBottom: '8px' }}>{item as string}</li>
              ))}
            </ul>
          ) : (
            <div style={{ color: textMuted, fontSize: '14px' }}>Click to add house rules...</div>
          )}
        </div>
      );

    case 'testimonials':
      return (
        <div style={{ padding: '24px' }}>
          <h2 style={{ margin: '0 0 16px', fontSize: '18px', fontFamily: headingFont, color: primary }}>Testimonials</h2>
          {Array.isArray(c.items) && c.items.length > 0 ? (
            <div style={{ display: 'flex', flexDirection: 'column', gap: '16px' }}>
              {c.items.map((item: unknown, i: number) => (
                <div key={i} style={{ padding: '16px', background: 'rgba(128,128,128,0.1)', borderRadius: '8px', border: '1px solid rgba(128,128,128,0.2)' }}>
                  <div style={{ fontSize: '14px', color: text }}>{(item as {text: string}).text || 'Great stay!'}</div>
                  <div style={{ fontSize: '12px', color: textMuted, marginTop: '8px' }}>— {(item as {author: string}).author || 'Guest'}</div>
                </div>
              ))}
            </div>
          ) : (
            <div style={{ color: textMuted, fontSize: '14px' }}>Click to add testimonials...</div>
          )}
        </div>
      );

    case 'location':
      return (
        <div style={{ padding: '24px' }}>
          <h2 style={{ margin: '0 0 16px', fontSize: '18px', fontFamily: headingFont, color: primary }}>Location</h2>
          <p style={{ color: text, fontSize: '14px' }}>{c.description as string || 'Click to add location description...'}</p>
        </div>
      );

    case 'recap':
      return (
        <div style={{ padding: '24px' }}>
          <h2 style={{ margin: '0 0 16px', fontSize: '18px', fontFamily: headingFont, color: primary }}>Booking Details</h2>
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(2, 1fr)', gap: '12px', fontSize: '14px', color: text }}>
            <div><strong>Check-in:</strong> {c.checkIn as string || '15:00'}</div>
            <div><strong>Check-out:</strong> {c.checkOut as string || '11:00'}</div>
            <div><strong>Min nights:</strong> {c.minNights as number || 1}</div>
            <div><strong>Cancellation:</strong> {c.cancellationPolicy as string || 'Flexible'}</div>
          </div>
        </div>
      );

    case 'otherProperties':
      return (
        <div style={{ padding: '24px' }}>
          <h2 style={{ margin: '0 0 16px', fontSize: '18px' }}>Other Properties</h2>
          <div style={{ color: '#64748b', fontSize: '14px' }}>Click to configure...</div>
        </div>
      );

    default:
      return (
        <div className="section-placeholder">
          {sectionInfo?.icon} {sectionInfo?.label}
        </div>
      );
  }
}
